dataset:
  train_path: "/DATA/Tawheed/emotion_data/images//train"
  val_path: "/DATA/Tawheed/emotion_data/images//test"
  test_path: "/DATA/Tawheed/emotion_data/images//test"

training:
  batch_size: 128
  num_classes: 7
  epochs: 50
  learning_rate: 0.0001
  image_size: 224
  grayscale: true
  checkpoint_pattern: epoch={epoch}-val_acc={val_accuracy}-val_loss={val_loss}.pth
  pretrained: true

scheduler:
  use_scheduler: true
  mode: "min"
  factor: 0.2
  patience: 5

early_stopping:
  use_early_stopping: true
  patience: 10

ckpt_path: null